version: '3'

services:

    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.0"
        networks: [apisearch]
        ports:
            - 9200:9200
        environment:
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - "discovery.type=single-node"
            - "action.auto_create_index=-apisearch*,+*"

    search-server:
        image: "apisearchio/search-server:commit-447d5c6"
        networks: [apisearch]
        ports:
            - 8000:8000
        environment:
            APISEARCH_GOD_TOKEN: 0e4d75ba-c640-44c1-a745-06ee51db4e93
            APISEARCH_ENABLED_PLUGINS: elasticsearch
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_REFRESH_ON_WRITE: 1

networks:
    apisearch:
